source 'https://rubygems.org'
ruby "2.1.3"

gem 'activerecord'
gem 'mysql2'
gem 'google-api-client', '>= 0.6'
gem 'sinatra', '>= 1.3'
gem 'sinatra-reloader'
gem 'byebug'
gem 'rest_client'
gem 'email_reply_parser'
gem 'mail'
gem 'diffy'
gem 'differ'
gem 'sanitize'
