require_relative 'gmail_entity'
require_relative 'user'
require_relative 'label'
require_relative 'message_has_label'
require_relative 'duplicate'
require_relative 'msg_entity'
require_relative 'services/gmail_api_caller'
